name: sync
on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests	
    - name: sync
      run: |
        cp MiuiEURepository/sync.py .
        rm MiuiEURepository/*/*/*.md
        python sync.py
        cd MiuiEURepository
    - name: commit
      run: |
        git config --global user.email 1169942595@qq.com
        git config --global user.name A-JiuA
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
